@startuml
'https://plantuml.com/activity-diagram-beta

|ILEC/Service Provider|

start
#lightgreen:Designate/choose TNs 2;
#lightblue:Import TNs;
|Alianza|
#cyan:Add BYOTN Inventory process for each TN;
stop

@enduml
