@startuml
'https://plantuml.com/activity-diagram-beta

|ILEC/Service Provider|

start
#lightgreen:Choose TN to deactivate;
#lightblue:Deactivate TN from Account;
|Alianza|
#cyan:Deactivate BYOTN process;
stop

@enduml
