@startuml
'https://plantuml.com/activity-diagram-beta

|ILEC/Service Provider|

start
#lightgreen:Create, manage, and complete port;
#lightblue:Identify Account;
#lightblue:Add ported TN to Account;
|Alianza|
#cyan:Add BYOTN Inventory process for ported TN;
|Alianza|
:Provision ported TN E911 w/ Bandwidth;
:Provision ported TN in routing;
stop

@enduml
