@startuml
'https://plantuml.com/activity-diagram-beta

|ILEC/Service Provider|

start
#lightblue:Receive notice of port out;
#lightgreen:Manage, and complete port out;
#lightblue:Tell Alianza of port out and delete account;
|Alianza|
:Mark TNs as ported out;
#cyan:Delete account & deactivate all TNs process;
stop

@enduml
