@startuml
'https://plantuml.com/activity-diagram-beta

start

:User clicks "Forgot Password" on EUP;
:User enters email address;
:User marked as "must change password";
:Unique PW reset code & link created;
:Email w/ PW reset link (one time use) is sent;
:User clicks PW reset link;
:User is prompted for new password;
:User enters new password;
:Password is changed;
:Email sent to user about password change;
:User continues to portal;

stop

start


@enduml
