@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "PSTN" as pstn #BBC6C4
participant "SBC" as sbc #E3F2FD
participant Intermedia as im #DAA6AB
participant CPE2 as cpe2 #E3F2FD
participant Rater as rtr #E3F2FD

pstn -> sbc: INVITE \n To: DID1\n From: callerId
sbc -> cpe2: INVITE \n To: DID1\n From: callerId
note over cpe2 #ccc
  resolve DID1
  to account
end note
note over cpe2 #cyan
  determine DID1
  is routing to
  contact-center
end note
cpe2 -> sbc: INVITE \n To: DID1\n From: callerId\n (identifies Intermedia \nTrunk as target)
sbc -> im: INVITE \n To: DID1\n From: callerId
note over im #ccc
    route call to IVR,
    queue, or etc...
end note
... (call connects, progresses, and disconnects) ...
note over cpe2 #cyan
    publish session
    summary using
    contact center
    product-related
    data
end note
cpe2 -\ rtr: session summary
note over rtr #cyan
    process session
    summary and create
    CDRs tied to
    account properly
end note

@enduml