@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "PSTN" as pstn #BBC6C4
participant "SBC" as sbc #E3F2FD
participant Intermedia as im #DAA6AB
participant CPE2 as cpe2 #E3F2FD
participant Rater as rtr #E3F2FD

im -> sbc: INVITE\n To: TN1\n From: callerId\n LDN: DID1
sbc -> cpe2: INVITE\n To: TN1\n From: callerId\n LDN: DID1
note over cpe2 #cyan
    recognize DID1 and
    link to account
end note
note over cpe2 #cyan
    recognize TN1 is not
    on platform, and route
    off-net according to
    off-net routing rules
    for account
end note
cpe2 -> sbc: INVITE\n To: TN1\n From: callerId
sbc -> pstn: INVITE\n To: TN1\n From: callerId
... (call connects, progresses, and disconnects) ...
note over cpe2 #cyan
    publish session
    summary using
    contact center
    product-related
    data
end note
cpe2 -\ rtr: session summary
note over rtr #cyan
    process session
    summary and create
    CDRs tied to
    account properly
end note

@enduml